# Generated by Django 4.2.7 on 2024-01-06 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appStock', '0002_accesorio_stock_modelobicicleta_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesorio',
            name='creado',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='accesorio',
            name='modificado',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='modelobicicleta',
            name='creado',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='modelobicicleta',
            name='modificado',
            field=models.DateTimeField(null=True),
        ),
    ]
